import { SkillType } from './Skill';
import { type UnitClassDefinition, type UnitVariantDefinition } from './UnitClass';
import { type VersionId } from './Version';

export enum UnitTag {
    Classic = 'classic',
    Aquarion = 'aquarion',
    Elyrion = 'elyrion',
    Polaris = 'polaris',
    Cymanti = 'cymanti',
    Land = 'land',
    Naval = 'naval',
}

export const UNIT_VARIANT_DEFINITIONS: readonly UnitVariantDefinition[] = [
    {
        id: 'warrior-ship',
        label: 'Warrior Ship',
        health: 10,
    },
    {
        id: 'defender-ship',
        label: 'Defender Ship',
        health: 15,
    },
    {
        id: 'veteran-defender-ship',
        label: 'Veteran Defender Ship',
        health: 20,
    },
    {
        id: 'giant-ship',
        label: 'Giant Ship',
        health: 40,
    },
];

const shipVariantIds = UNIT_VARIANT_DEFINITIONS.map(v => v.id);

/** The second part of this type is here for the removed units. */
type UnitClassVersionDefinition = UnitClassDefinition | string;

const UNIT_DEFINITIONS_DIPLOMACY: readonly UnitClassVersionDefinition[] = [
    {
        id: 'warrior',
        label: 'Warrior',
        health: 10,
        attack: 2,
        defense: 2,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris, UnitTag.Cymanti ],
    }, {
        id: 'archer',
        label: 'Archer',
        health: 10,
        attack: 2,
        defense: 1,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
    }, {
        id: 'defender',
        label: 'Defender',
        health: 15,
        attack: 1,
        defense: 3,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris ],
    }, {
        id: 'rider',
        label: 'Rider',
        health: 10,
        attack: 2,
        defense: 1,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris ],
    }, {
        id: 'swordsman',
        label: 'Swordsman',
        health: 15,
        attack: 3,
        defense: 3,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris, UnitTag.Cymanti ],
    }, {
        id: 'catapult',
        label: 'Catapult',
        health: 10,
        attack: 4,
        defense: 0,
        skills: [ SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris ],
    }, {
        id: 'knight',
        label: 'Knight',
        health: 10,
        attack: 3.5,
        defense: 1,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris ],
    }, {
        id: 'giant',
        label: 'Giant',
        health: 40,
        attack: 5,
        defense: 4,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Classic ],
    }, {
        id: 'polytaur',
        label: 'Polytaur',
        health: 15,
        attack: 3,
        defense: 1,
        skills: [ SkillType.Fortify ],
        tags: [ UnitTag.Land, UnitTag.Elyrion ],
    }, {
        id: 'boat',
        label: 'Boat',
        health: undefined,
        attack: 1,
        defense: 1,
        skills: [],
        tags: [ UnitTag.Naval, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
        variantIds: shipVariantIds,
    }, {
        id: 'ship',
        label: 'Ship',
        health: undefined,
        attack: 2,
        defense: 2,
        skills: [],
        tags: [ UnitTag.Naval, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
        variantIds: shipVariantIds,
    }, {
        id: 'battleship',
        label: 'Battleship',
        health: undefined,
        attack: 4,
        defense: 3,
        skills: [],
        tags: [ UnitTag.Naval, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
        variantIds: shipVariantIds,
    }, {
        id: 'amphibian',
        label: 'Amphibian',
        health: 10,
        attack: 2,
        defense: 1,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Aquarion ],
    }, {
        id: 'tridention',
        label: 'Tridention',
        health: 15,
        attack: 3,
        defense: 1,
        skills: [ SkillType.Fortify, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Aquarion ],
    }, {
        id: 'crab',
        label: 'Crab',
        health: 40,
        attack: 4,
        defense: 4,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Aquarion ],
    }, {
        id: 'navalon',
        label: 'Navalon',
        health: 30,
        attack: 4,
        defense: 4,
        skills: [],
        tags: [ UnitTag.Naval, UnitTag.Elyrion ],
    }, {
        id: 'dragon-egg',
        label: 'Dragon Egg',
        health: 10,
        attack: 0,
        defense: 2,
        skills: [ SkillType.Fortify ],
        tags: [ UnitTag.Land, UnitTag.Elyrion ],
    }, {
        id: 'baby-dragon',
        label: 'Baby Dragon',
        health: 15,
        attack: 3,
        defense: 3,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Elyrion ],
    }, {
        id: 'fire-dragon',
        label: 'Fire Dragon',
        health: 20,
        attack: 4,
        defense: 3,
        skills: [ SkillType.Splash ],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Elyrion ],
    }, {
        id: 'ice-archer',
        label: 'Ice Archer',
        health: 10,
        attack: 0.1,
        defense: 1,
        skills: [ SkillType.Freeze, SkillType.Fortify ],
        tags: [ UnitTag.Land, UnitTag.Polaris ],
    }, {
        id: 'battle-sled',
        label: 'Battle Sled',
        health: 15,
        attack: 3,
        defense: 2,
        skills: [ SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Polaris ],
    }, {
        id: 'mooni',
        label: 'Mooni',
        health: 10,
        attack: 0,
        defense: 2,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Polaris ],
    }, {
        id: 'ice-fortress',
        label: 'Ice Fortress',
        health: 20,
        attack: 4,
        defense: 3,
        skills: [ SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Polaris ],
    }, {
        id: 'gaami',
        label: 'Gaami',
        health: 30,
        attack: 4,
        defense: 4,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Polaris ],
    }, {
        id: 'hexapod',
        label: 'Hexapod',
        health: 5,
        attack: 3,
        defense: 1,
        skills: [ SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'kiton',
        label: 'Kiton',
        health: 15,
        attack: 1,
        defense: 3,
        skills: [ SkillType.Poison, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'phychi',
        label: 'Phychi',
        health: 5,
        attack: 1,
        defense: 1,
        skills: [ SkillType.Poison, SkillType.Surprise, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Cymanti ],
    }, {
        id: 'raychi',
        label: 'Raychi',
        health: 15,
        attack: 3,
        defense: 2,
        skills: [ SkillType.Explode, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Naval, UnitTag.Cymanti ],
    }, {
        id: 'exida',
        label: 'Exida',
        health: 10,
        attack: 3,
        defense: 1,
        skills: [ SkillType.Poison, SkillType.Splash, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'doomux',
        label: 'Doomux',
        health: 20,
        attack: 4,
        defense: 2,
        skills: [ SkillType.Explode, SkillType.Promote ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'centipede',
        label: 'Centipede',
        health: 20,
        attack: 4,
        defense: 3,
        skills: [],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'segment',
        label: 'Segment',
        health: 10,
        attack: 2,
        defense: 2,
        skills: [ SkillType.Explode ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    }, {
        id: 'cloak',
        label: 'Cloak',
        health: 5,
        attack: 0,
        defense: 0.5,
        skills: [ SkillType.Infiltrate ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris, UnitTag.Cymanti ],
    }, {
        id: 'dagger',
        label: 'Dagger',
        health: 10,
        attack: 2,
        defense: 2,
        skills: [ SkillType.Surprise ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris, UnitTag.Cymanti ],
    }, {
        id: 'dinghy',
        label: 'Dinghy',
        health: 5,
        attack: 0,
        defense: 0.5,
        skills: [ SkillType.Infiltrate ],
        tags: [ UnitTag.Naval, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
    }, {
        id: 'pirate',
        label: 'Pirate',
        health: 10,
        attack: 2,
        defense: 2,
        skills: [ SkillType.Surprise ],
        tags: [ UnitTag.Naval, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion ],
    }, {
        id: 'mind-bender',
        label: 'Mind Bender',
        health: 10,
        attack: 0,
        defense: 1,
        skills: [ SkillType.Convert ],
        tags: [ UnitTag.Land, UnitTag.Classic, UnitTag.Aquarion, UnitTag.Elyrion, UnitTag.Polaris ],
    }, {
        id: 'shaman',
        label: 'Shaman',
        health: 10,
        attack: 1,
        defense: 1,
        skills: [ SkillType.Convert ],
        tags: [ UnitTag.Land, UnitTag.Cymanti ],
    },
] as const;

const UNIT_DEFINITIONS_OCEAN: readonly UnitClassVersionDefinition[] = [
    'navalon',
] as const;

export const UNIT_DEFINITIONS: Record<VersionId, readonly UnitClassVersionDefinition[]> = {
    diplomacy: UNIT_DEFINITIONS_DIPLOMACY,
    ocean: UNIT_DEFINITIONS_OCEAN,
};
