name: deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v4

      - run: echo $DOT_ENV > .env
        env:
          DOT_ENV: ${{ vars.DOT_ENV }}

      - run: npm install

      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

      - uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
          artifact_name: github-pages

